http:
  routers:
    hageplan-router:
      rule: "PathPrefix(`/projects/hageplan`)"
      service: hageplan-service
      middlewares:
        - strip-hageplan-prefix
      tls:
        certResolver: le

  middlewares:
    strip-hageplan-prefix:
      stripPrefix:
        prefixes:
          - "/projects/hageplan"

  services:
    hageplan-service:
      loadBalancer:
        servers:
          - url: "http://hageglede:8000"